[phases.setup]
nixPkgs = ["python3", "postgresql_16.dev", "gcc", "libxslt.dev", "tesseract"]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[start]
cmd = "uvicorn product_management:app --host 0.0.0.0 --port $PORT"