[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "web"
source = "."

[services.web]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"

[[services]]
name = "postgres"
source = "postgres:15"