[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
ENVIRONMENT = "production"
DATABASE_URL = "${{DATABASE_URL}}"
PORT = "${{PORT}}"

[[services]]
name = "product-management-api"

[services.source]
repo = "SombathSOAN/product-management"
branch = "main"

[services.variables]
PYTHON_VERSION = "3.11"
WEB_CONCURRENCY = "1"